### PR TITLE
updates for 1Password 4 and 5

### PR DESCRIPTION
**Pull request by skurfer**
- fixed some icons
- add type definition
- add support for opening URLs
- provide a default path to the logins
- change wording and documentation (now that only logins are supported)
- remove unused keys and types
- clean-up
- bump version to 3.0.0

A bit late, but… yep.

### CODE REVIEW

**Comment by pjrobertson** [comment]
Wow, can't believe I've only just seen this. Really sorry :-(

**Comment by pjrobertson** [comment]
So I think what's made things keep working for me is that I'm still using the .agilekeychain format for the keychain (which is created when setting up '[Dropbox Sync](https://support.1password.com/1passwordanywhere/)' (not that I'm actually using dropbox to sync!).

I'm doing this so that I can sync to a web server and use the archaic 1password.html file to access my keychain online.

**Comment by pjrobertson** [comment]
Ok, I've found the location of the 3rd party integration app for MAS version:

`~/Library/Containers/2BUA8C4S2C.com.agilebits.onepassword-osx-helper/Data/Library/3rd Party Integration/bookmarks-default.json`
I don't know if the `2BUA8C4S2C` prefix to the Bundle ID is fixed or now, we'd need somebody else with the MAS version to check.

I can confirm that setting it in this way works. I'm happy to remove my code (which works for the .agilekeychain format) and require people to do this 3rd party integration business, but I think we'd need a bit smarter code to detect which version of 1Pwd is being used, and to set the `bookmarks-default.json` pref accordingly.

**Comment by skurfer** [comment]
When I worked on this, I remember trying to figure out a way to cover all the cases and then remembered that you already had a file picker in the prefs. 😀

I got my info from [discussion on the list][1].

But yeah, figuring out that location isn’t the most user friendly thing. If we can get them closer automatically, that would be good.

[1]: https://groups.google.com/d/msg/blacktree-quicksilver/vuHZtyspRI0/FvQ95Pbz7oAJ

**Comment by pjrobertson** [comment]
I just replied in the gGroup about the MAS path to the 3rd party json
file... but I see in the link you just posted Leveebreaks already mentions
this path, and it's the same! So - I guess we can safely use this as the
default, then fall back to the non-MAS path if this doesn't exist.

**Comment by pjrobertson** [comment]
OK, I've made changes I hope will now work. @skurfer can you test out #7 and let me know?

Also take a look over the code incase there's something else you want to add

**Pull request closed without merging**
